#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>

/*
Anagramas
Os vilões costumam disfarçar-se para cometer todo o tipo de maldades. Os disfarces são tão bons que são quase impossíveis de detetar. Felizmente que os vilões costumam usar nomes que são anagramas do seu verdadeiro nome, isto é, usam as mesmas letras que o nome original.

Pediram-te que escrevas um programa para detetares anagramas.

Input
O teu programa deve ler:

Uma linha contendo um inteiro positivo N que é o nº de casos
Por cada caso o teu programa deve ler:
Uma linha contendo o nº de possíveis candidatos, K
Uma linha contendo o nome do vilão
K linhas contedo possíveis nomes do vilão disfarçado
Todos os nomes ocupam menos de 100 caracteres, podem conter espaços e estão em maiúsculas.

Output
O teu programa deve imprimir uma linha por cada caso com os nºs das linhas que são anagramas do nome do vilão. Caso não haja ninguém nestas condições, deverá imprimir o valor -1
*/

int isAnagrama(char *s, char *a) {
  int posicao = 0;
  int fst_ABC[26] = {0}, snd_ABC[26] = {0};

  for (posicao = 0; s[posicao] != '\0'; posicao++) {

    if (s[posicao != ' ']) {
      fst_ABC[s[posicao] - 'A'] += 1;
    }
  }

  for (posicao = 0; a[posicao] != '\0'; posicao++) {
    if (a[posicao != ' ']) {
      snd_ABC[a[posicao] - 'A'] += 1;
    }
  }

  for (posicao = 0; posicao < 26; posicao++) {

    if (fst_ABC[posicao] != snd_ABC[posicao]) {
      return 0;
    }
  }
  return 1;
}

int main() {
  int Ncasos, Nstrings;
  char enemyName[100], anagrama[100];

  if (scanf("%d ", &Ncasos)) {

    // printf("Ncasos: %d\n",Ncasos);

    for (int i = 0; i < Ncasos; i++) {

      if (scanf("%d ", &Nstrings)) {

        if (fgets(enemyName, 100, stdin)) {

          int count = 0;

          for (int j = 1; j <= Nstrings; j++) {

            if (fgets(anagrama, 100, stdin)) {

              anagrama[strcspn(anagrama, "\n")] = '\0';

              if (isAnagrama(enemyName, anagrama) == 1) {

                if (count != 1) {

                  printf("%d", j);
                  count = 1;

                } else {

                  printf(" %d", j);
                }
              }
            }
          }

          if (count != 1) {

            printf("-1\n");

          } else {

            printf("\n");
          }
        }
      }
    }
  }
  return 0;
}





/*
Exemplo
Sample Tests
Input 1
2
5
INIGO MONTOYA
TONY ONIGIOMA
ANTHONY MIOGI
ANTONY MIOOGI
ANTONY MIO GIO
OTIMO GYNO NAI
2
JOAO PESTANA
MISTER SANDMAN
JOANA TESPANA
Output 1
1 3 4 5
-1
Input 2
10
8
PAXE DYXIME NOCEJY GABUSL
PYCI NEJO SURE LIGU GASUXIQY
LUXASA JEMEN CIBEPY GOXYD
SINU DEXE TOQA RYJI RAGOQAMI
MPABY DCIGU XASEXEJELYNO
MIQA LITU HUQI XYZA DADOLYTA
XUPXE LAJGE BASE MINODYCY
JYDELABE XGIS PYXAMUNECO
BUGU KICA XATIWY WIRO RYNIRO
10
XNUHU ZALA NUNURUTYNO
GEWU POFE SUPUCA JOKUPO
SIFI HOQYTI NIPO VYSYKA
WYTE VEZI QEFO VUFEQIXI
MEZE RUMO BAPA WUQAMADE
KUQIJAXA GOFU KUSERESO
GOGE PAJI PYPI XEVAJAPI
NANU LARUNO NYXUZUTHU
KOXU FIKU FASIMU FYVEJA
XUNU NUNA RUHALZYTUNO
WEPAHA QIDI KEXUBEHOFO
9
GOCE ZEBU TETEBYCO
FEHI DUTU HEHYQOQO
TOZE GYCE TUBECEBO
BOTO BECE ZYCEGETU
CUZO BETOCY BETEGE
QELU RAHOWONYDOCE
BEBOCE CUTO ZETEGY
VIRUBY RYVE BOXEME
BISE GYLU HUKIWYJE
SUTY TIQA WAJUREBO
10
FACO HYMO TEOCALE
FOTY LECO HECAMOA
ZIWA DORE CUPOSENO
MADA JEZY MYLUQIZO
GOSEBE KIJYRYDUPE
GAGI LODI VIDETUDU
ZOGI PIXE BUNILAQA
PYMO JOKI GIPECYLY
CEFE JICE NEGYHIRA
CIPY MEWY QOTIPOSO
OCOMEFE HOLATYCA
10
ZAJI LEEGI SUKAGY
DAVU FYPA HOKIGIXO
LICYMO BUBECINIRO
UGAZA SEGELYJIKI
LEGU ZIKE YJAGISA
JIGE ZIUSY LEGAKA
RENI NYME NYHYXELI
ELYJU GISE KAZAGI
LIJE GAIZUGEKYSA
JISE LIGA KAYZEGU
JYLYWA WOTUVAPEZE
10
MISI HIEO SAGICI
DABU HOQY NUNENEVO
SISA HIII MOGECI
SOHI GEICAISIMI
FALO VULY BIDARYCO
IISA MISE COGIHI
QYGOCO JAHA CAJOMY
XAPO ZUJE PYMOWELA
MEGO SIHIIISACI
CIII SIHI MEGOSA
QEBE BABY VIPICOXY
8
VUNI RYWO GUZU VEKE JIWIYCU
NEZI KIVUCU VUGIWO WURYJYE
CIWIGU VYRE WUVU UJENIZYKO
NEWOE WUKI VUVU CYRY ZUGIJI
CUGY WUKO WUZIJU VYRENIVEI
TIBA NYLI KEBO ZIBALA JILUBA
TEVE HAJY VUMO XUCYLA GODAJE
RUGYNY JUVI CIKE ZOIWUWEVU
PAFA SUFA BEKY JUBY SOPYXAPU
9
REDA TARU LIZYXAWUNOY
ZARY RUDUXYI LATENAWO
WARA ZIXU ULYRE TYDANO
JUDO GOME ZISA VOLEPUQY
POFA BORE WATU XYVUBEQY
TEWUNAO ZIRAXA DYLURY
RUNI YTUXA WEDO LYRAZA
ZUWO RATY RIDAANELUXY
DURY NAXU ZALA REOWYTI
NECY NOWI GOTI KIJASIPE
9
REZY TYVE KYKQU PHIRODUSU
JANO PUXUJA PAKY ZYPOGELYQU
GYBY NOHU BOFI WYSU LYXEZEZY
RDYSU REZU TUKO PYKEHYQIV
QEVY KEZUKO TUHDY PYRURIS
GAXI FUZODI RAPE FYMYGURAGO
VORPU HERY KYZUSE TIDYQKU
DYHO VEZRY KEKU SUQYRUPTI
NYHOPO BAHA CORUBALI JIXADE
MOWOZI XUMYCY NEZISUCEQAVA
12
RUGE LYJI LEXBI BAQERIWZERU
RAKY MYLO MUNA QIQUHIQYJYTOZY
GOKY FIRA DUFA FOHIXI KYHIWAPE
RQELU LRAWEGIRI JIBE ZUBYXE
JIXIRO ZIRERU HYTI KURYWEXIHI
FEXU GYDYNY COSU NYBI FEPEFUVO
RIZI BYXJA LERI QUWGU BELERE
REJQE LABIBE ZELXYRU WIRIGU
TYQO KYBE HERO DEXUKIKA VIRELO
RRIBERE LEJI GYQU LAZEXBUWI
RURIBE XALI RIBZE JEQYLEGUW
XELU DOTY RIVO MYCU ZABY XINIVY
REWI GEQI RLUJE XYLIZE BURAB
Output 2
2 4 6 7
7 9
2 3 4 6
1 10
3 4 5 7 8 9
2 3 5 8 9
1 2 3 4 7
1 2 5 6 7 8
3 4 6 7
3 6 7 9 10 12
Input 3
10
11
RATU DODO MIHE DUNI PIFTAJUWY
XIHUFA ZAPU FOGA DIKI ROMYVOLU
FYRI VEXI BISAGE FEXI MIFERAFO
SICE CEQU HYRU GAJI TIMU BIBIHE
REMU DIDO NATA WHUPO TIFIDUJY
GURI WEXU DUXA JUPA JISO WALATU
DUMENUFAWI DITRU HODI JYPATO
TOWU JUHE PIFA MATU DYDO NIRID
JUDI MIWU TTONAFO PIRU HEDYDA
TYJU POHADU TIFRO NAMI DUWIDE
FUMEWO DAHINI DJUPI TORUTYDA
NORO DAJU TUDAPI MYFE TUWDIHI
9
MYRO SAJOVY ZYUDUZUGO
WELE SOBU JENY ZURETISU
GEQE TUCU ROJI KUQAMIRO
SUYZA ZOMO VOGU DUJYRY
VOMO SYZO JUYGU ZURADY
OZOVUSA MUZO RYJYGUDY
FEZE RYQISI POLY PIHYLI
MAGO ZELAGO QYPI RYKIZI
ZYMA VOGU RUSY OZUDYJO
ROVODYSA GUJY ZUMUYZO
11
DOMO ZUMU FAHENEIBY
PYPY CAVA JIZI WATYQU
JYFE JOPE HETY NOPYGE
BOIME HODY ZEMUNAFU
NUMU FEHI DAMOEZOBY
BEMI SIFO RERE TOQERU
RABI PERY BEMEQETOPI
JICEHA HETA SUKIWOWU
LUKO GOWOGIRY TYRINA
LOZO GAVE DAJE MAHYPY
ZYNA FEHU EMOMUBODI
FUHE DONO ZYMUMIEBA
10
TUSA XARUNU REBA SPUCUFURVY
PUBYRESU NASU XCAR RAVUFUTU
SUTU RCUXA VURU SAFRA NYBEPU
TERY WIDU WUVY RUGUBO MOTEVOHE
FAPO PEHA TEJI TAPA DUBIRUZOCA
BUNU SURU CVPAFATU SARERUXY
XEGE NULY BEFO GEKUPY CYHEJYHU
FYZE FYLA KORITA PEHAGA VINEVI
REPA NURU BYRU VUFU SUXSATCA
SECTA XURU FAVSU BUPUNARURY
DYLE SOQYLU BYRO VOTU WOQIMYJU
11
WAHO LUNUHU BANE CYME HALYVBHO
TYXIFA VOJU GOREKO GOSI SEVEHYBE
NEWU HYBY LUBA HHAL MUCE VONOHA
CYMU NAHHU HYNO WLEHA LEVOBUBA
HUBUBA HUHA NEHO MECY LWAVONLY
LBEHU HUHY LAVE NUWA BYNCOMOHA
VAWBO HECU LEHA LONA MYHHYNUBU
CYBE HENUH HUHO BALY VANMALOWU
WYJYJE BOPU COSI CACA DIQITYMIMU
XINO JYHU QOQUSUCU SICI LYWUZUQU
TADO QASU XIFEJO GEJY PARY XIVIRA
CACE WOBOMY GIPA QURY LAPE RUPYKI
8
GALY BEXO TUUCAGEQU
XELA GOGU UCUQYTEBA
LUQE GECA TUBYGOUXA
BEOQU TACAXU LUGYGE
UGOBAXE LUGEQYCATU
GACO GULEEXU BYQATU
GEBUQY TULO CEXAGAU
EGULA CEXU QATYBOGU
CIVO PYSU TYTO MUHULO
11
LINUHI SETA KUWU JUTYXU
KAMOGU NURU CITI HEWUSO
KEHA LYXY LOMYRE QUCIXO
KUJA HYXEWU TULUSITINU
LUTU TEKI WYSI HAJUNUXU
NUKI LUXY WUSU JUTIHATE
HOXAMI PEXA RYDU BELUDI
HETA RUTO XOFO VIBULYWE
MAMA WUKO WOKI CANIHUNU
WYLA SUTI XUJU KINUTEHU
TISI KEJULA TUWU HYXUNU
FEBUNA JOBE LILO WIQOFE
9
PICU LAFE MIXE DIWA VELUSE
PUVE MALI WEXU SEFACEDILI
LIPELE WEFA MIDE VACISUXU
TYGY SEPU KEBY BINY NADOQU
LEWE XIDE FEVI LAPA MUSICU
MAXU SIDE LAVI PULI CEFEWE
GINI KOFY LUBY HYVE LUJYHU
TEBE HYLUJI BINA KIQEFIWE
BOZI TEXY NYQI PAJIPEBOXY
CUVA XEPE WADI FELI LUSEMI
9
KAKI QOOY KODU KYVU ZUSYXU
KEBA XIGU PEBO NIBAVA WYPUGU
SOKU XUZU OVYQO KYKADYUKI
QUVUKO YKYSU ZODI KAYXUKO
TAJO GUPY XUHUSO ZYGI MIVYPU
VOQY XUKI KADU KUZO UYKYSO
KYKU VIKO XUSU ZYYUKODAQO
VOXY ZASO KYQYU KUIKUDOKU
SOXI KYKO KUUYQOVUKADYZU
UKOKOXUDO IVYSAKU KUZYQY
10
QUCU BOSIRA UFUJERO
XACA ZYXE VATI KIZAHO
GUHO ZOKOPA QUBAXACO
QURA FEOCIRU BUJUSO
JUPE XAGE PABI SOBEXA
FOBU JUUCO QIRERUSA
QUWI FYKA RYBE NIJIZO
ABERO FUJI QURUSOCU
BABO ZOJYJA ROKAZEJY
FUQI RUACU SEROBUJO
NUPY WONE ZYNA COCAFY
Output 3
4 6 7 8 9 10 11
3 4 5 8 9
3 4 10 11
1 2 5 8 9
2 3 4 5 6 7
1 2 3 4 5 6 7
3 4 5 9 10
1 2 4 5 9
2 3 5 6 7 8 9
3 5 7 9
Input 4
10
11
UDIETATE ZAHOMO
GOPO KENU NYHUTIVE
ZOTO AHETIEMADU
IOTU ZADE MEHATO
ZIRE WAQE ZAKOHILU
ZIRY ZUXY DITIXECE
MATA OZUHOTEEDI
HILY ZYTOMYSEWEJA
MODA IHETUTAOZE
DALO COKY MAHONAXI
DALYLY CAZI ZUTOSY
DAZO TUTAHEIOME
11
LAFBE XYVE FOFI GAJETUDU
XOFE FUDABE TYLI GAVEFJU
PYVA XOJIRU DILA GOZOGUBI
GELDY JATA FUXI FEFOVUBE
FIDE CEHA ZUVE WECA KIVALA
ZUSE HYBY GODOSECIWUBAGY
VOFAXE JULU TAGE FIDBEFY
XAFEDETO FUJE FUGIBVALY
TIRE SOKYVI BYXU NEZOMOGU
DENU WIBA SYNUDE SYNEDEDA
NYVI WIBE JUMYME TYTOROZY
VADE BIFE FEJA FYTULOXGU
12
MIFIMY FUMO QEWO TYHEVICY
VOFI FECO MEWI QUMI HYTYMY
RASO TIJU RESI VUQA MOHASY
LAWI QOPADE WISO GATAPOHU
KUBO PURO JAVE COJIRUDUPU
FIHY COTE QEMI WOMU MYVIFY
CEFY TIWI MYVY FUMO HEQOMI
GUBAMO LOPA LYZY KUZIPIJI
GOJE CEQU VIQE HUXI PEMAQY
COMIQI WYTEVO MUMIHYFYFE
FECY TIMI WEFOHY MYMOQUVI
HAJOZA PIFA NISA XOFURYPA
CIFO QYFY VIHI MYTO WEMEMU
8
FAGZ NODE PURY MEWU ZAVIKEMA
HYLAJU QOLO XAHI BYKA WEBESYXA
NADWU KZAZE PEGU MOFI REMAVY
PARO DETE HONOTE WURO KIBENOFO
XEMO HUSY MEWANU CAKY WODIRAHE
CYNA CILI RAHA SAQE LODA WERYPE
NZYKIGAWAVE MOFMUDE ZERAPU
DUGE ROMA VNEZA ZAKI WUMEPYF
TAGE WEPY LEVU BOKU JUMEGOBAMO
11
LEBBI PATSI KIVU JAMA KIFADUGO
TIVAFI GAKA SLADBI JEMUPIBUKO
DIWA MIGY DUCI PAMY DIXO TYCIQYCU
JDABI BAPO MALUVI KEKIT SAGIFU
VYKU BYSI BYCY LYQU VEWYDI DUHIQY
RUWI FIDI QOHUCY BITO HEHYHIGYVI
PADO TBEBI LIVA KUSU KAMI GIJAF
BGIMO LEFA VUSU DIJI BATIKAPKA
BAJA PKULI MBAGEKA FIVISODITU
KUHY JIDIQY PAKEHUCO HOGY MASUTU
BIKI MKUSA LEVI TOBA JUDAGIPFA
VAQO LYCY TIDY FICI TOVIKALINOHE
12
JONI WYXANYHY TECA REZENIFO
XENIWENO HYRA FICY JOZATYNE
XITO NYZE NENORIFAWECAJYHY
RANA FEHY TOCY XENO JENIWYZI
FORA WEZO JYNA NYNE CITEHYXI
XORO HIPY WUQI LINI PALOSAHY
FYDY TYFI XUBU TYRI RONYZITA
XENA WYTEFY ZYNI HONIRECOJA
DOGE XEBYMOQACU HICU DEPERE
CYNO WAFE NEHI NOJY TIZYXERA
ZUGA JIME CURE ROMA ROTASAZA
TERI ZYWY JACY XINO NEFOHANE
PYCU ZAFO DINA XEBUDO JEKOCI
9
TEIXA IJYCUXUMU
MANU SOPO VITOGYXY
XENY FUNI NIZOWIJE
LEMIBU REZY SEDUTE
MUUTI JYCAXEXIU
MIPE BEKI NOWERUQY
EUJYTA CIMIXUXU
QAXY ZAHA FOSOZOWY
VIVY LAJE PIQYBYBI
YXICA JUXI TEMUU
8
FIVA DOTI VUNIVYS NICICA
XAKY CUJE GONI SIRO POTIXU
VAHO WELYZY SAVU ZOQAHEWU
WYNO WYHU ZONU TISY FUQOPO
CANA CIFI SIDI VVUVYTONI
SELO MOKE KOCEJUBI XEQYZO
CVIVYFI VANI DANUTICISO
JUGO LUTY RYRE LEZI XYZUNU
ZUSI JEZY PIVU GIFA WAHIGO
8
VRAQE GEDKI POFIPYDIHE
PPEDY VQIHI RIDOFEKEGA
ZYCE HIDY KANI QERY JIHEZO
PIQE HPDI DAFE VOKIREGY
LAFICY NETE FUQO LOFEHUGA
GODDI PYHA QPERE KEFIVI
HIGIBO WOMI LAJY KABUNOLA
DAPP KEDI VERY HIFOQEGI
WIZUXA ZUHO MIGUWADAKICO
8
LACURU POQA RERGE KIRODE
RERPERI LAQO KADE GOCURU
SYKOWONA POPI XYCUHEQUZO
PUQE ROGA LERO REDRIKUCA
QIXY DUCO HEVU WAGA NALOMI
HEGOZU XUMO BOLU WYFYSUFI
COGA DULU RQOPI REREREKA
RIROC QAGA LERE KEDURUPO
QIRE RARA LOPUDU COGKERE
Output 4
2 3 6 8 11
1 3 6 7 11
1 5 6 9 10 12
2 6 7
1 3 6 7 8 10
1 2 3 4 7 9 11
4 6 9
4 6
1 3 5 7
1 3 6 7 8
Input 5
10
12
CIBO DOZO GOHOVAVI
COBA ZODOGOVIHOVI
VOZA VOBI DOCOGOHI
CULU CAJU HIXAKASI
ZODIBO COVOVOGIHA
GIZA VIFU XAKONAFA
RANU BULU LOWYFOGI
ZOHA HOCUWI KOBARO
DOZA GOVO VIHIBOCO
GOZOVOCO BIDIVOHA
JYSU VYGY JONEGOQE
ZOVOHA BOCO GODIVI
VODO CIHOVO GABIZO
9
GYQI KUSU MAWOCY PANOSUKUMO
PYVY GESOZE ZYZIMU QUHUWITE
PYSOSO KUMA COQI GUMU NAKUWY
MUQE JYXU QINE LOQO TIPYSIZI
WUPY MOKA KANY QUSU GUCOMOSI
KUNO MISU KOQUPO MYSU GYCAWA
WUPI MAGY SUMO NOSU QUKAKYCO
MIZA LAVAVEZU NOHY KYKUBELU
GURU TINU BAJA NIPU MUDASYWY
WAMI POSU KUNO QYGO MUCYKASU
12
SOZU VOQU LYLU NANOY
FAPA GEPA RORE RYNEWA
KIPI RYXYFE HUNYJUPU
VUQU NYSO ZOLANUYLO
VYWU ZYPO XAJEMEFOLY
VUNO NYZU LOYLUQOSA
QYLO VAUZU NOLONUSY
RADA DYQI HIVUPANYXE
GONA XOJE NOJOVIFEDI
LUSO LYZONA OQUVUNY
LYOZO LUNU QYNOSAVU
LAGISA LOPI TEROPUVA
ROFY BEFA GIGY ZISATY
9
VYNU TINE VAYTU PEBO HAPEU
BOTE UPYNIVYPA NEVETAUHU
PEBA VEUO NEPU VIHYTUTYNA
ZUSU GINO NYME HETI CYTEZOKE
WUMO PEDY KYJU DORI FOQONASI
BIHODY TECUMEHAVA ZOKINUVE
TEUPUPY VENO BEINA TUHYVA
WAFE LIGOWE PILA BYBASUWOWO
PANEVY PEVU INATU TUEBOHY
SUKAZY SYRY SOHA TIREMUMEPY
11
XIENY MYBEMOUNAFY
MYBY FYIXO ENANEMU
EOBY NYFE MYNAXIMU
DYPE QYZO WIWACIJEXI
XEIMY NEMYOBANUFY
JEBO DUDU GAZU WAREQE
MOBA NYXI FEUNEMYY
DYNA PAMI VAGI ROWAJY
RINUVO BYZA LAFUCEJA
MYKU QAXE ZUTE JEKIRE
FYNYMY XEONE BIMUA
ZYPA XAGY MENA HOKYDI
12
TOFU LIKU BUGU POPAJYMAQY
TUPUKA QAMY BOJI GUPULYFO
BEKU NACO GALO GECUHIFEHY
FAQE BAWU PUJO MYZIPYQYDO
CYWO QECU GOVA KUZU LENAHE
PYFU GUQOBATAPU MOLUJIKY
GUPA POMILAKU QUBYJOTUFY
VEGE PEKOMA DIRA FYNOXONA
RIPO TYBU KEQYZE XOSEDEMI
WOWI KUMO HIQI VUPI BENIQU
HYZO SOPIDE POXA JISAPOSA
FOQU LIMY BUGU PAPAJYKUTO
TUGUQOPI FYKY JUBAPAMULO
8
COTO JUXI SALY BODO GUNATO
TYLO BOCUDA JOSI NUTAXOGO
XUDO JYTO NUCO SOTALABOGI
JOSA TICA BUNOXO DOLYGOTU
MOXO CEDA QOVE DOQO TUJOKO
LUNO PUGO HEBU WIMI BEREPU
NANA FIRA FAGAXU NUZYBYXO
XANI JUHU JAPU SAHY LETOCI
FILI NIFIKA CYZI RORIGEDO
10
XUBE TEGA BERU SYGEAIQUMA
GAME BEGY AQIXA SUBUETERU
BYGE BUUQI XUGA METAARESE
TALE TUCU RUZI CUDU GUPAJAPO
TARU BUUSA EQEGA XYBEMIGE
ESIRU EMAGUBYTE GAQAXEBU
REPEWI BUNE TUSOLE QUVEPUTO
LEKI QOWO VICU CEQYFU COSEWE
BYXI GIXA HIJE VUSE LOSULIGI
BETA UAMY GIRE XEGA QUBUSE
XARU UTASAE BEBI QEMYGEGU
10
REGO YCYIZUHYRU
IYZUGYRUHYCERO
CYRY GIEU RYZUHO
VORO FYWE BANUVYNY
HYCYZU URYGIROE
PINE NIVA KAFIROSU
ERYZI CUHO GURYY
NIWA JYCEKEKIKUNO
ICERU UHYZORYGY
HYYCI GOERYRUZU
REGY RYHU ZYOUCI
12
FECI RISUR ZYTIZIDU
DUDO RISI KEQAPEMODI
RFUREZY TISIDUCIZI
CUSE LYTITYPA JYTYCE
XOMY BACE JOBIDESAKU
CYTE RUSI ZIZIDFIRU
MIJY FIGALA RYFABUCU
NACE ZELEJE FOTARATE
TYZE ZISI DRURUCIFI
DYTE RUZSI RUZICIFI
ZUCIRU ZIRI SDITEFY
DIFE RYTU ZIZICSURI
SEFI CIZU ZYRTIRIDU
Output 5
1 2 4 8 9 11 12
2 4 5 6 9
3 5 6 9 10
1 2 6 8
1 2 4 6 10
1 5 6 11 12
1 2 3
1 2 4 5 9 10
1 2 4 6 8 9 10
2 5 8 9 10 11 12

*/